USE CSE_4A_221;

-------------LAB_6_CURSOR-------------

CREATE TABLE PRODUCT(
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(250) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL
)

-- CREATE OR ALTER PROCEDURE PR_PRODUCT_INSERT
-- @PROID INT,
-- @PRONAME VARCHAR(250),
-- @PRICE DECIMAL(10,2)
-- AS
-- BEGIN
--     INSERT INTO PRODUCT VALUES
--     (@PROID,@PRONAME,@PRICE)
-- END

-- EXEC PR_PRODUCT_INSERT 1,'SMARTPHONE',35000;
-- EXEC PR_PRODUCT_INSERT 2,'LAPTOP',65000;
-- EXEC PR_PRODUCT_INSERT 3,'HEADPHONES',5500;
-- EXEC PR_PRODUCT_INSERT 4,'TELEVISION',85000;
-- EXEC PR_PRODUCT_INSERT 5,'GAMING CONSOLE',32000;
SELECT * FROM PRODUCT;
-------------PART-A---------------
-- 1. Create a cursor Product_Cursor to fetch all the rows from a products table. 

DECLARE @PRODUCT_ID INT,@PRODUCT_NAME VARCHAR(250),@PRICE DECIMAL(10,2)

DECLARE PRODUCT_CURSOR CURSOR
FOR SELECT PRODUCT_ID,PRODUCT_NAME,PRICE FROM PRODUCT
OPEN PRODUCT_CURSOR
FETCH NEXT FROM PRODUCT_CURSOR INTO @PRODUCT_ID,@PRODUCT_NAME,@PRICE

WHILE @@FETCH_STATUS = 0
    BEGIN
        PRINT 'PRODUCT_ID:'+CAST(@PRODUCT_ID AS VARCHAR)+
              ' , PRODUCT_NAME:'+@PRODUCT_NAME+
              ' , PRICE:'+CAST(@PRICE AS VARCHAR)+'.'
        FETCH NEXT FROM PRODUCT_CURSOR INTO @PRODUCT_ID,@PRODUCT_NAME,@PRICE        
    END

CLOSE PRODUCT_CURSOR
DEALLOCATE PRODUCT_CURSOR;

-- 2. Create a cursor Product_Cursor_Fetch to fetch the records in form of ProductID_ProductName.(Example: 1_Smartphone) 

DECLARE @PRODUCT_INFO VARCHAR(300)

DECLARE PRODUCT_CURSOR_FETCH CURSOR
FOR SELECT CAST(PRODUCT_ID AS VARCHAR) + '_'+PRODUCT_NAME FROM PRODUCT
OPEN PRODUCT_CURSOR_FETCH
FETCH NEXT FROM PRODUCT_CURSOR_FETCH INTO @PRODUCT_INFO

WHILE @@FETCH_STATUS = 0
    BEGIN
        PRINT @PRODUCT_INFO
        FETCH NEXT FROM PRODUCT_CURSOR_FETCH INTO @PRODUCT_INFO        
    END

CLOSE PRODUCT_CURSOR_FETCH
DEALLOCATE PRODUCT_CURSOR_FETCH


-- 3. Create a Cursor to Find and Display Products Above Price 30,000. 
DECLARE @PRODUCT_ID INT, @PRODUCT_NAME VARCHAR(250), @PRICE DECIMAL(10,2);

DECLARE PRODUCT_PRICE_GT30_CURSOR CURSOR
FOR SELECT PRODUCT_ID, PRODUCT_NAME, PRICE FROM PRODUCT WHERE PRICE > 30000;

OPEN PRODUCT_PRICE_GT30_CURSOR;

FETCH NEXT FROM PRODUCT_PRICE_GT30_CURSOR INTO @PRODUCT_ID, @PRODUCT_NAME, @PRICE;

WHILE @@FETCH_STATUS = 0
BEGIN 
    PRINT 'PRODUCT_ID: ' + CAST(@PRODUCT_ID AS VARCHAR) +
          ', PRODUCT_NAME: ' + @PRODUCT_NAME +
          ', PRICE: ' + CAST(@PRICE AS VARCHAR);

    FETCH NEXT FROM PRODUCT_PRICE_GT30_CURSOR INTO @PRODUCT_ID, @PRODUCT_NAME, @PRICE;
END;

CLOSE PRODUCT_PRICE_GT30_CURSOR;
DEALLOCATE PRODUCT_PRICE_GT30_CURSOR;

-- 4. Create a cursor Product_CursorDelete that deletes all the data from the Products table.

DECLARE @PRODUCT_ID INT

DECLARE PRODUCT_CURSOR_DELETE CURSOR
FOR SELECT PRODUCT_ID FROM PRODUCT
OPEN PRODUCT_CURSOR_DELETE
FETCH NEXT FROM PRODUCT_CURSOR_DELETE INTO @PRODUCT_ID

WHILE @@FETCH_STATUS = 0
    BEGIN
        DELETE FROM PRODUCT WHERE PRODUCT_ID = @PRODUCT_ID
        FETCH NEXT FROM PRODUCT_CURSOR_DELETE INTO @PRODUCT_ID
    END

CLOSE PRODUCT_CURSOR_DELETE
DEALLOCATE PRODUCT_CURSOR_DELETE
